import {test,expect} from 'bun:test'
import {mkdtemp,rm,writeFile,unlink,mkdir} from 'node:fs/promises'
import {tmpdir} from 'node:os'
import {join} from 'node:path'
import {execFileSync} from 'node:child_process'
import {createRun,readRun} from '../src/runs.ts'
import {prepareCheckpoint,publishCheckpoint,type CheckpointIntent} from '../src/checkpoints.ts'
async function fixture(change:(cwd:string,git:(...args:string[])=>string)=>Promise<void>){const home=await mkdtemp(join(tmpdir(),'checkpoint-')),cwd=join(home,'writer'),remote=join(home,'remote.git'),root=join(home,'runs');await mkdir(cwd);const g=(...args:string[])=>execFileSync('git',args,{cwd,encoding:'utf8',stdio:['ignore','pipe','pipe']}).trim();g('init','-b','main');g('config','user.email','fixture@example.test');g('config','user.name','Fixture');await writeFile(join(cwd,'allowed.txt'),'base');g('add','.');g('commit','-m','base');const base=g('rev-parse','HEAD');g('init','--bare',remote);g('--git-dir',remote,'symbolic-ref','HEAD','refs/heads/main');g('remote','add','origin',remote);g('push','origin','HEAD:main');g('checkout','-b','feat/1-work');await change(cwd,g);const head=g('rev-parse','HEAD');const authorities=[{approvalId:'approved',source:{kind:'github-comment' as const,repositoryId:'R_repo',issueNodeId:'I_parent',commentId:'12',bodySha256:'a'.repeat(64)}}];const run=await createRun({root,repo:'o/r',issue:1,parent:null,checkout:cwd,branch:'feat/1-work',baseSha:base,headSha:head,stage:'implement',harness:'fixture',model:'fixture',effort:'high',execution:null,approvalBindings:authorities,recordBinding:null,approvalRefs:[],policyDigest:'b'.repeat(64),claimToken:crypto.randomUUID(),startedAt:new Date().toISOString(),taskKey:{repo:'o/r',issue:1,taskId:'1-T1',scopeDigest:'c'.repeat(64)},activeElapsedMs:null,taskOwner:null,agentAccountOwner:null,accountRef:null,waitReason:null,machine:null,sharedClaim:null,checkpoint:null,remoteEffectCoverage:{kind:'unmanaged-possible',reasonCode:'fixture'}});const intent:CheckpointIntent={id:'approved-task-backup',repo:'o/r',repositoryId:'R_repo',remote:'origin',remoteUrl:remote,branch:run.branch,baseRef:'refs/heads/main',baseSha:base,scopeDigest:run.taskKey.scopeDigest,paths:['allowed.txt'],approvalBindings:authorities};return{home,cwd,root,run,intent,head,g,remote}}
test('allowed committed history reaches only approved exact task ref and readback persists',async()=>{const f=await fixture(async(cwd,g)=>{await writeFile(join(cwd,'allowed.txt'),'changed');g('add','.');g('commit','-m','safe progress')});try{const controller={root:f.root,verifyAuthority:async()=>{}};const candidate=await prepareCheckpoint({run:f.run,approvedIntent:f.intent,headSha:f.head},controller);const result=await publishCheckpoint(candidate,controller);expect(result.kind).toBe('acknowledged');expect(f.g('ls-remote','origin','refs/heads/feat/1-work').split(/\s/)[0]).toBe(f.head);const stored=await readRun(f.root,f.run.runId);expect(stored.pendingDelivery[0]?.exportProof?.closureDigest).toBe(candidate.exportProof.closureDigest);expect(stored.checkpoint?.headSha).toBe(f.head)}finally{await rm(f.home,{recursive:true,force:true})}},15000)
for(const kind of ['secret','outside'] as const)test(`removed ${kind} history refuses before exporting any object`,async()=>{let forbidden='';const f=await fixture(async(cwd,g)=>{const path=kind==='secret'?'allowed.txt':'forbidden.txt';await writeFile(join(cwd,path),kind==='secret'?'credential-canary-DO-NOT-EXPORT':'outside');g('add','.');g('commit','-m','intermediate');forbidden=g('rev-parse','HEAD');if(kind==='secret')await writeFile(join(cwd,path),'clean');else await unlink(join(cwd,path));g('add','-A');g('commit','-m','clean final')});try{await expect(prepareCheckpoint({run:f.run,approvedIntent:f.intent,headSha:f.head},{root:f.root,verifyAuthority:async()=>{}})).rejects.toThrow();expect(f.g('ls-remote','origin','refs/heads/feat/1-work')).toBe('');expect(()=>f.g('--git-dir',f.remote,'cat-file','-e',forbidden)).toThrow()}finally{await rm(f.home,{recursive:true,force:true})}},15000)
