import {test,expect} from 'bun:test'
import {mkdtemp,rm,stat,readFile,writeFile} from 'node:fs/promises'
import {tmpdir} from 'node:os'
import {join} from 'node:path'
import {createRun,transitionRun,readRuns,parseRun,classifyRecovery,nextQuotaCheck,type RunInput} from '../src/runs.ts'
const input=(root:string):RunInput=>({root,repo:'o/r',issue:1,parent:null,checkout:root,branch:'feat/1-work',baseSha:'a'.repeat(40),headSha:null,stage:'implement',harness:'fixture',model:'fixture',effort:'high',execution:null,approvalBindings:[],recordBinding:null,approvalRefs:[],policyDigest:'b'.repeat(64),claimToken:crypto.randomUUID(),startedAt:new Date().toISOString(),taskKey:{repo:'o/r',issue:1,taskId:'1-T1',scopeDigest:'c'.repeat(64)},activeElapsedMs:null,taskOwner:null,agentAccountOwner:null,accountRef:null,waitReason:null,machine:null,sharedClaim:null,checkpoint:null,remoteEffectCoverage:{kind:'unmanaged-possible',reasonCode:'fixture'}})
test('private durable records survive reload; competing stale CAS cannot overwrite',async()=>{const root=await mkdtemp(join(tmpdir(),'runs-'));try{const r=await createRun(input(root));expect((await stat(join(root,r.runId,'run.json'))).mode&0o777).toBe(0o600);const outcomes=await Promise.allSettled([transitionRun(r.runId,1,{activeElapsedMs:100},root),transitionRun(r.runId,1,{activeElapsedMs:200},root)]);expect(outcomes.filter(o=>o.status==='fulfilled')).toHaveLength(1);const [saved]=await readRuns(root);expect(saved!.generation).toBe(2);expect([100,200]).toContain(saved!.activeElapsedMs);await expect(transitionRun(r.runId,2,{approvalBindings:[]} as never,root)).rejects.toThrow('immutable')}finally{await rm(root,{recursive:true,force:true})}})
test('terminal identity/cause and interrupted recovery never imply replay',async()=>{const root=await mkdtemp(join(tmpdir(),'runs-'));try{const r=await createRun(input(root));await expect(transitionRun(r.runId,1,{state:'terminal'},root)).rejects.toThrow();const done=await transitionRun(r.runId,1,{state:'terminal',terminationCause:'succeeded',finishedAt:new Date().toISOString()},root);await expect(transitionRun(r.runId,done.generation,{state:'running'},root)).rejects.toThrow();expect(classifyRecovery({state:'running',ownerAlive:false,pendingDelivery:[]})).toEqual({state:'interrupted',replay:false});expect(()=>parseRun({...done,schemaVersion:7})).toThrow()}finally{await rm(root,{recursive:true,force:true})}})
test('quota checks back off without a task elapsed allowance',()=>{expect(nextQuotaCheck(0,0)).toBe(900000);expect(nextQuotaCheck(4,0)).toBe(3600000);expect(nextQuotaCheck(0,0,42)).toBe(42)})
